apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: sit737-prac6p-app
          imagePullPolicy: Never  # 🔥 THIS IS THE FIX
          ports:
            - containerPort: 3000
